server:
  port: 8080

spring:
  profiles:
    default: dev-mysql
  flyway:
    default-schema:
      - dotcompta
    enabled: true
    locations:
      - classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:3000/
        allowed-methods: GET, POST, PUT, DELETE
